name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: ruby
          package-name: json_spotter
          bump-minor-pre-major: true
          version-file: "lib/json_spotter/version.rb"